### ISSUE TITLE
Tell the Difference 😄 

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit-2.0#32]
Create a new branch from the initial commit of this repo and name it `initial-branch`.
Then answer the following question in your info.md` file.

**Ques - ** You will see that some repo on GitHub has a `main` branch as their main but some have a `master` branch as their main branch. So, please explain in which case Git/GitHub creates `main` as the main branch and in which case it creates `master` as the main branch.

Now add and commit your answer to this question and create a PR from this initial branch to this repo's `dummy-branch`.
Condition: You must use the SHA key of the initial commit in any one of the git commands that you will use to complete this task.
PR which will be unable to fulfill the condition can be rejected.
If your `info.md` file is not there, then you have to make a new one.

**Comment by vedant-z** [comment]
claim

**Comment by ABHAY0O7** [comment]
@vedant-z You already have 3 issues assigned bro, first complete any one of them, until then you can't claim this one.

**Comment by anshgeez31** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by vishalola** [comment]
claim

**Comment by Finesse-734** [comment]
claim

**Comment by ABHAY0O7** [comment]
@anshgeez31 Go for it 👍🏽 
If you didn't complete the task within two days, then it will be again open for a claim.

**Comment by Aman1143** [comment]
claim

**Comment by Siddhant-Agarwal4583** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by Aman1143** [comment]
claim

**Comment by BINGABABA** [comment]
claim

**Comment by ABHAY0O7** [comment]
> claim

@RibhavBansal  Go for it 👍🏽
If you didn't complete the task within two days, then it will be again open for a claim.

**Comment by Aman1143** [comment]
@ABHAY0O7 Sir i claim first right now

**Comment by Siddhant-Agarwal4583** [comment]
Clai

**Comment by Aman1143** [comment]
Sorry sir

**Comment by ABHAY0O7** [comment]
> @ABHAY0O7 Sir i claim first right now

No, Ribhav claimed first, after it was open for a claim.
![Screenshot from 2022-12-22 02-20-30](https://user-images.githubusercontent.com/75938293/209000664-39d5a837-412b-4f53-a6ae-fcb1714695d8.png)

**Comment by antsharma** [comment]
Claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by akshatsgh** [comment]
claim

**Comment by ABHAY0O7** [comment]
@akshatsgh  Go for it 👍🏽
If you didn't complete the task within two days, then it will be again open for a claim.

**Comment by Kali-Decoder** [comment]
claim

**Comment by ABHAY0O7** [comment]
This task was successfully solved in #77 by @akshatsgh
