### ISSUE TITLE
Push Me 📌 

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit-2.0#57]
Create a directory inside `CONTRIBUTORS` of any name. 
Now add, commit and push your changes to the repo.
So simple, just do that.
⌚ 
⌚ 
But in doing so you will face a problem.
`I want that problem (you faced above) and the reason for that problem i.e. why you are facing that problem` inside your `info.md` file.
Now add, commit and push your answer and make a PR.

**Comment by anshgeez31** [comment]
claim

**Comment by Aman1143** [comment]
claim

**Comment by ABHAY0O7** [comment]
@anshgeez31 and @Aman1143 you both can do this task. The first one to do the task correctly on the first attempt will get the points. Otherwise, the issue will be again open for claim.

**Comment by antsharma** [comment]
Claim

**Comment by akshayw1** [comment]
Claim

**Comment by ABHAY0O7** [comment]
@anshgeez31 successfully solved this issue in #58
