### ISSUE TITLE
Find and Add 🙈 

### ISSUE THREAD

**Issue by ABHAY0O7** [opencodeiiita/GoGit-2.0#68]
"I am a basic git-related file which is present in almost all the repositories over GitHub but not present on this repo"
Guess the file "I" in the above phrase and add it to this repo.

First, find this file and add it to this repo and make a PR, then I will tell you the further steps of this task.
The deadline to make a correct PR for this half of the task is today.

**Comment by MistyRavager** [comment]
Claim

**Comment by RibhavBansal** [comment]
claim

**Comment by ABHAY0O7** [comment]
> Claim, since its open till now :)

Yup, it's open till now bcz nobody claimed it.
Go for it @MistyRavager

**Comment by Kali-Decoder** [comment]
claim

**Comment by ABHAY0O7** [comment]
This task was successfully completed in #73 by @MistyRavager .
